[package]
name = "tg-dump-word-cloud"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
regex = "1.11.1"
rust-stemmers = "1.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
wordcloud-rs = "0.1.17"
